// api/humanize.js — Vercel serverless function
// Numbers are locked BEFORE Claude sees the text, restored AFTER

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { text, mode } = req.body;

  if (!text || typeof text !== "string") {
    return res.status(400).json({ error: "No text provided" });
  }

  // ── Step 1: Lock all numbers, dates, citations ──────────────
  const protectedItems = [];
  const protectedText = text.replace(
    /(\$[\d,]+(?:\.\d+)?(?:\s?(?:billion|million|trillion|thousand))?|\d+(?:,\d{3})*(?:\.\d+)?(?:\s?(?:billion|million|trillion|thousand))?%?|\bQ[1-4]\s?\d{4}\b|\b(?:19|20)\d{2}\b|\([A-Za-z]+,\s?(?:19|20)\d{2}\))/gi,
    (match) => {
      protectedItems.push(match);
      return `NUM${protectedItems.length - 1}X`;
    }
  );

  // ── Step 2: Build mode-specific instruction ─────────────────
  const modeInstructions = {
    "data-safe":  "Rewrite this in a natural, conversational but professional tone.",
    "academic":   "Rewrite this in a formal academic tone suitable for a research paper or thesis.",
    "business":   "Rewrite this in a professional business report tone.",
    "executive":  "Rewrite this as a concise executive summary with confident, direct language.",
    "resume":     "Rewrite this in a strong, action-oriented resume/cover letter tone.",
    "plain":      "Rewrite this in simple plain English that anyone can understand.",
  };

  const toneInstruction = modeInstructions[mode] || modeInstructions["data-safe"];

  // ── Step 3: Call Claude API ─────────────────────────────────
  const prompt = `You are a professional writing editor. Your job is to rewrite text so it sounds completely human-written and natural — not like it was generated by AI.

${toneInstruction}

CRITICAL RULES:
1. Every token in the format NUM0X, NUM1X, NUM2X etc. is a protected value (number, date, percentage, or citation). You MUST keep every single one exactly as-is, in the same position in the sentence. Do not change, move, or remove them.
2. Vary sentence length — mix short punchy sentences with longer ones.
3. Use natural transitions and connective phrases a real human writer would use.
4. Avoid words like: "notably", "it is worth noting", "furthermore", "moreover", "in conclusion", "it is important to note", "delve", "leverage" (unless in resume mode), "utilize".
5. Do not add new facts, statistics, or information.
6. Do not add any explanation or preamble — output ONLY the rewritten text.

Text to rewrite:
${protectedText}`;

  let claudeOutput;
  try {
    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 1024,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      console.error("Claude API error:", data);
      return res.status(500).json({ error: "Claude API error", detail: data });
    }

    claudeOutput = data.content[0].text;
  } catch (err) {
    console.error("Fetch error:", err);
    return res.status(500).json({ error: "Failed to reach Claude API" });
  }

  // ── Step 4: Restore all protected values ────────────────────
  let restored = claudeOutput.replace(/NUM(\d+)X/g, (match, index) => {
    return protectedItems[parseInt(index, 10)] !== undefined
      ? protectedItems[parseInt(index, 10)]
      : match;
  });

  // ── Step 5: Final cleanup ───────────────────────────────────
  restored = restored
    .replace(/\s+/g, " ")
    .replace(/\s+([.,;:!?])/g, "$1")
    .replace(/([.,;:!?])([A-Za-z])/g, "$1 $2")
    .replace(/(%)([A-Za-z])/g, "$1 $2")
    .trim();

  return res.status(200).json({ result: restored });
}
